# Generated by Django 4.0.6 on 2022-07-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_rename_text_topic_name_topic_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='title',
        ),
    ]
