# Generated by Django 4.0.6 on 2022-07-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_rename_name_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default=1, upload_to='static'),
            preserve_default=False,
        ),
    ]
