# Generated by Django 4.0.6 on 2022-07-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_alter_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='foto'),
            preserve_default=False,
        ),
    ]
