# Generated by Django 4.0.4 on 2022-09-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0018_alter_topic_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='heading',
        ),
        migrations.AddField(
            model_name='entry',
            name='header',
            field=models.CharField(blank=True, max_length=50, verbose_name='header'),
        ),
    ]
