# Generated by Django 4.0.4 on 2022-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0019_remove_entry_heading_entry_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True, verbose_name='text'),
        ),
    ]
