# Generated by Django 4.1.1 on 2022-09-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0021_alter_entry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(default='opa', verbose_name='text'),
        ),
    ]
